### ISSUE TITLE
Wakeup problem after sleep

### ISSUE THREAD

**Issue by hjames1** [im1ke/Huawei_MatebookD15-2018-Hackintosh#2]
Hi, im1ke!
  Thank you for your sharing. This EFI works well for me. However , there is a problem about sleep. The machine can not wake up properly after sleep, and also , if I just close the lid, the screen would not turn off.
  Can you help me out?

**Comment by hjames1** [comment]
by the way,  I was using DW1820A

**Comment by im1ke** [comment]
Hi! I do not observe a similar problem in myself.
